version: '3'
services:
  dusk-1:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - dusk_TestNetworkEnabled=1
      - dusk_VerboseLoggingEnabled=1
      - dusk_ControlPortEnabled=1
      - dusk_ControlSockEnabled=0
    ports:
      - "6274:5274"
      - "127.0.0.1:6275:5275"
  dusk-2:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - dusk_TestNetworkEnabled=1
      - dusk_VerboseLoggingEnabled=1
  dusk-3:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - dusk_TestNetworkEnabled=1
      - dusk_VerboseLoggingEnabled=1
  dusk-4:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - dusk_TestNetworkEnabled=1
      - dusk_VerboseLoggingEnabled=1
  dusk-5:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - dusk_TestNetworkEnabled=1
      - dusk_VerboseLoggingEnabled=1
