version: '3'
services:
  dusk-1:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - dusk_TestNetworkEnabled=1
      - dusk_VerboseLoggingEnabled=1
      - dusk_ControlSockEnabled=0
      - dusk_ControlPortEnabled=1
      - dusk_TraverseNatEnabled=0
      - dusk_NodePublicAddress=dusk-1
    volumes:
      - ./bin:/root/dusk/bin
      - ./lib:/root/dusk/lib
      - ./index.js:/root/dusk/index.js
      - ./package.json:/root/dusk/package.json
    ports:
      - "6274:5274"
      - "127.0.0.1:6275:5275"
  dusk-2:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - dusk_TestNetworkEnabled=1
      - dusk_VerboseLoggingEnabled=1
      - dusk_TraverseNatEnabled=0
      - dusk_NodePublicAddress=dusk-2
      - dusk_NetworkBootstrapNodes=http://dusk-1:5274
    volumes:
      - ./bin:/root/dusk/bin
      - ./lib:/root/dusk/lib
      - ./index.js:/root/dusk/index.js
      - ./package.json:/root/dusk/package.json
  dusk-3:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - dusk_TestNetworkEnabled=1
      - dusk_VerboseLoggingEnabled=1
      - dusk_TraverseNatEnabled=0
      - dusk_NodePublicAddress=dusk-3
      - dusk_NetworkBootstrapNodes=http://dusk-1:5274
    volumes:
      - ./bin:/root/dusk/bin
      - ./lib:/root/dusk/lib
      - ./index.js:/root/dusk/index.js
      - ./package.json:/root/dusk/package.json
  dusk-4:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - dusk_TestNetworkEnabled=1
      - dusk_VerboseLoggingEnabled=1
      - dusk_TraverseNatEnabled=0
      - dusk_NodePublicAddress=dusk-4
      - dusk_NetworkBootstrapNodes=http://dusk-1:5274
    volumes:
      - ./bin:/root/dusk/bin
      - ./lib:/root/dusk/lib
      - ./index.js:/root/dusk/index.js
      - ./package.json:/root/dusk/package.json
  dusk-5:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - dusk_TestNetworkEnabled=1
      - dusk_VerboseLoggingEnabled=1
      - dusk_TraverseNatEnabled=0
      - dusk_NodePublicAddress=dusk-5
      - dusk_NetworkBootstrapNodes=http://dusk-1:5274
    volumes:
      - ./bin:/root/dusk/bin
      - ./lib:/root/dusk/lib
      - ./index.js:/root/dusk/index.js
      - ./package.json:/root/dusk/package.json
